name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubicloud
            platform: linux/amd64
          - runner: ubicloud-standard-2-arm
            platform: linux/arm64

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./docker
        file: ./docker/Dockerfile
        platforms: ${{ matrix.platform }}
        push: true
        tags: |
          ghcr.io/nackophilz/fankai_utilitaire:${{ github.event.inputs.image_tag || 'latest' }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          ghcr.io/nackophilz/fankai_utilitaire:${{ github.sha }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}

  merge-manifests:
    needs: build
    runs-on: ubicloud
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create and push multi-arch manifest
      run: |
        docker buildx imagetools create -t ghcr.io/nackophilz/fankai_utilitaire:${{ github.event.inputs.image_tag || 'latest' }} \
          ghcr.io/nackophilz/fankai_utilitaire:${{ github.event.inputs.image_tag || 'latest' }}-amd64 \
          ghcr.io/nackophilz/fankai_utilitaire:${{ github.event.inputs.image_tag || 'latest' }}-arm64
        docker buildx imagetools create -t ghcr.io/nackophilz/fankai_utilitaire:${{ github.sha }} \
          ghcr.io/nackophilz/fankai_utilitaire:${{ github.sha }}-amd64 \
          ghcr.io/nackophilz/fankai_utilitaire:${{ github.sha }}-arm64
