name: Nettoyage des artefacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  delete-artifacts:
    runs-on: ubicloud
    permissions:
      actions: write
    steps:
      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days
